-- MySQL Script generated by MySQL Workbench
-- Sun Aug 29 00:05:03 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema repair_shopdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema repair_shopdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `repair_shopdb` DEFAULT CHARACTER SET utf8 ;
USE `repair_shopdb` ;

-- -----------------------------------------------------
-- Table `repair_shopdb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repair_shopdb`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `repair_shopdb`.`Masters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repair_shopdb`.`Masters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `repair_shopdb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repair_shopdb`.`Orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_name` VARCHAR(100) NOT NULL,
  `order_price` DECIMAL(9,2) NOT NULL,
  `order_date` DATE NOT NULL,
  `order_status` VARCHAR(60) NOT NULL,
  `paymant_status` VARCHAR(60) NOT NULL,
  `id_user` INT NOT NULL,
  `id_master` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Orders_Users_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_Orders_Masters1_idx` (`id_master` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Users`
    FOREIGN KEY (`id_user`)
    REFERENCES `repair_shopdb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Masters1`
    FOREIGN KEY (`id_master`)
    REFERENCES `repair_shopdb`.`Masters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
